### ISSUE TITLE
Infinite $digest Loop

### ISSUE THREAD

**Issue by lpsBetty** [nervgh/angular-file-upload#538]
Unfortunately I don't know what causes these errors, but I changed nothing on angular or angular-file-upload... I just did a fresh `bower install` (maybe that caused the problem, I can't tell for sure)

what I did recently was updating bower to `1.6.5`., and updating npm to `3.3.9`
I am using angular-file-upload 1.1.6 and even if I update to the latest version (2.2.0) the problem persists.

First there is an '[cpws](http://errors.angularjs.org/1.4.7/ng/cpws)' error than the '[Infinite $digest Loop](http://errors.angularjs.org/1.4.7/$rootScope/infdig?p0=10&p1=%5B%5D)'
Here is the whole stacktrace:
````
angular.js:12477 Error: [ng:cpws] http://errors.angularjs.org/1.4.7/ng/cpws
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:6:416
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:11:279)
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:12:173)
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:13:89)
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:12:173)
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:13:89)
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:11:458)
    at ha (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:12:329)
    at n.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:130:468)(anonymous function) 
@ angular.js:12477(anonymous function) 
@ angular.js:9246n.$digest 
@ angular.js:15844n.$apply 
@ angular.js:16097i._render.value 
@ FileUploader.js:325i.addToQueue.value 
@ FileUploader.js:82i.onChange.value 
@ FileSelect.js:67n.event.dispatch 
@ jquery-2.1.3.min.js:3r.handle 
@ jquery-2.1.3.min.js:3

angular.js:12477 Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.7/$rootScope/infdig?p0=10&p1=%5B%5D
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:6:416
    at n.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:131:331)
    at n.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:133:512)
    at r.i._render.value (http://translate.dev.lingohub.com:9000/bower_components/angular-file-upload/dist/angular-file-upload.min.js:6:5226)
    at r.i.addToQueue.value (http://translate.dev.lingohub.com:9000/bower_components/angular-file-upload/dist/angular-file-upload.min.js:6:2739)
    at t.i.onChange.value (http://translate.dev.lingohub.com:9000/bower_components/angular-file-upload/dist/angular-file-upload.min.js:6:15918)
    at HTMLInputElement.n.event.dispatch (http://code.jquery.com/jquery-2.1.3.min.js:3:6444)
    at HTMLInputElement.r.handle (http://code.jquery.com/jquery-2.1.3.min.js:3:3219)(anonymous function) 
@ angular.js:12477(anonymous function) 
@ angular.js:9246n.$apply 
@ angular.js:16099i._render.value 
@ FileUploader.js:325i.addToQueue.value 
@ FileUploader.js:82i.onChange.value 
@ FileSelect.js:67n.event.dispatch 
@ jquery-2.1.3.min.js:3r.handle 
@ jquery-2.1.3.min.js:3
angular.js:38 Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.7/$rootScope/infdig?p0=10&p1=%5B%5D(anonymous function) 
@ angular.js:38n.$digest 
@ angular.js:15864n.$apply 
@ angular.js:16097i._render.value 
@ FileUploader.js:325i.addToQueue.value 
@ FileUploader.js:82i.onChange.value 
@ FileSelect.js:67n.event.dispatch 
@ jquery-2.1.3.min.js:3r.handle 
@ jquery-2.1.3.min.js:3
````

Maybe someone has the same problem?

**Comment by lpsBetty** [comment]
Sorry it was the own code which caused the problem.. didn't saw that in the stacktrace :(

**Comment by nervgh** [comment]
:ghost:

**Comment by lpsBetty** [comment]
I hate misleading stacktraces :D :-1:

**Comment by nervgh** [comment]
Don't worry about it :smile_cat:
"Не who makes no mistakes, makes nothing"
