### ISSUE TITLE
[$injector:nomod] Module 'angularFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.6.4/$injector/nomod?p0=angularFileUpload

### ISSUE THREAD

**Issue by jayprajapati857** [nervgh/angular-file-upload#834]
I have done exactly what is there in introduction part but still getting this error can anyone help me i am new to angular.

the error Message is : 

angular.js:66 Uncaught Error: [$injector:modulerr] Failed to instantiate module elephant due to:
Error: [$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
Error: [$injector:nomod] Module 'angularFileUpload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.4/$injector/nomod?p0=angularFileUpload
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:66:12
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:2262:17
    at ensure (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:2183:38)
    at module (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:2260:14)
    at Object.angular.module (http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:775:16)
    at addReg (http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:117:46)
    at Object.forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at addReg (http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:123:29)
    at http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:128:17
    at Object.forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=oc.lazyLoad&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'angularFileUpload'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fnomod%3Fp0%3DangularFileUpload%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2262%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2183%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2260%3A14)%0A%20%20%20%20at%20Object.angular.module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A775%3A16)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A117%3A46)%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A123%3A29)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A128%3A17%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:66:12
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4920:15
    at forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at loadModules (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4880:5)
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4898:40
    at forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at loadModules (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4880:5)
    at createInjector (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4802:19)
    at doBootstrap (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1914:20)
    at bootstrap (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1935:12)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=elephant&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20oc.lazyLoad%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'angularFileUpload'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fnomod%3Fp0%3DangularFileUpload%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2262%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2183%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2260%3A14)%0A%20%20%20%20at%20Object.angular.module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A775%3A16)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A117%3A46)%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A123%3A29)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A128%3A17%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fmodulerr%3Fp0%3Doc.lazyLoad%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'angularFileUpload'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.6.4%252F%2524injector%252Fnomod%253Fp0%253DangularFileUpload%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A66%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A2262%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A2183%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A2260%253A14)%250A%2520%2520%2520%2520at%2520Object.angular.module%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A775%253A16)%250A%2520%2520%2520%2520at%2520addReg%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A117%253A46)%250A%2520%2520%2520%2520at%2520Object.forEach%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A403%253A20)%250A%2520%2520%2520%2520at%2520addReg%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A123%253A29)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A128%253A17%250A%2520%2520%2520%2520at%2520Object.forEach%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A403%253A20)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4920%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4880%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4898%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4880%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4802%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A1914%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A1935%3A12)
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:66:12
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:2262:17
    at ensure (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:2183:38)
    at module (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:2260:14)
    at Object.angular.module (http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:775:16)
    at addReg (http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:117:46)
    at Object.forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at addReg (http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:123:29)
    at http://192.168.0.222:8020/Content/js/vendor/ocLazyLoad/ocLazyLoad.js:128:17
    at Object.forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=oc.lazyLoad&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'angularFileUpload'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fnomod%3Fp0%3DangularFileUpload%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2262%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2183%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2260%3A14)%0A%20%20%20%20at%20Object.angular.module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A775%3A16)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A117%3A46)%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A123%3A29)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A128%3A17%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:66:12
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4920:15
    at forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at loadModules (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4880:5)
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4898:40
    at forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at loadModules (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4880:5)
    at createInjector (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4802:19)
    at doBootstrap (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1914:20)
    at bootstrap (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1935:12)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=elephant&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20oc.lazyLoad%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'angularFileUpload'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fnomod%3Fp0%3DangularFileUpload%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2262%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2183%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A2260%3A14)%0A%20%20%20%20at%20Object.angular.module%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A775%3A16)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A117%3A46)%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20addReg%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A123%3A29)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2FocLazyLoad%2FocLazyLoad.js%3A128%3A17%0A%20%20%20%20at%20Object.forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fmodulerr%3Fp0%3Doc.lazyLoad%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'angularFileUpload'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.6.4%252F%2524injector%252Fnomod%253Fp0%253DangularFileUpload%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A66%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A2262%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A2183%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A2260%253A14)%250A%2520%2520%2520%2520at%2520Object.angular.module%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A775%253A16)%250A%2520%2520%2520%2520at%2520addReg%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A117%253A46)%250A%2520%2520%2520%2520at%2520Object.forEach%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A403%253A20)%250A%2520%2520%2520%2520at%2520addReg%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A123%253A29)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252FocLazyLoad%252FocLazyLoad.js%253A128%253A17%250A%2520%2520%2520%2520at%2520Object.forEach%2520(http%253A%252F%252F192.168.0.222%253A8020%252FContent%252Fjs%252Fvendor%252Fangular%252Fangular.js%253A403%253A20)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4920%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4880%3A5)%0A%20%20%20%20at%20http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4898%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4880%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A4802%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A1914%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2F192.168.0.222%3A8020%2FContent%2Fjs%2Fvendor%2Fangular%2Fangular.js%3A1935%3A12)
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:66:12
    at http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4920:15
    at forEach (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:403:20)
    at loadModules (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4880:5)
    at createInjector (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:4802:19)
    at doBootstrap (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1914:20)
    at bootstrap (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1935:12)
    at angularInit (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:1820:5)
    at HTMLDocument.<anonymous> (http://192.168.0.222:8020/Content/js/vendor/angular/angular.js:33367:5)
    at fire (http://192.168.0.222:8020/Content/js/vendor/jquery/jquery-2.2.4.js:3187:31)
(anonymous) @ angular.js:66
(anonymous) @ angular.js:4920
forEach @ angular.js:403
loadModules @ angular.js:4880
createInjector @ angular.js:4802
doBootstrap @ angular.js:1914
bootstrap @ angular.js:1935
angularInit @ angular.js:1820
(anonymous) @ angular.js:33367
fire @ jquery-2.2.4.js:3187
fireWith @ jquery-2.2.4.js:3317
ready @ jquery-2.2.4.js:3536
completed @ jquery-2.2.4.js:3552

**Comment by jayprajapati857** [comment]
its done there was mistake by me just need to load that /angular-file-upload.js first to have this working
